### ISSUE TITLE
Ice Lake support has landed!

### ISSUE THREAD

**Issue by tomasdev** [dortania/dortania.ml#2]
Well, not really. But it's now in MacInfoPkg :-)

So perhaps an update is needed on https://dortania.ml/hackintosh/updates/2020/03/22/catalina-10154.html

https://github.com/acidanthera/MacInfoPkg/commit/203a0edfda6f9e0776c0ea7df09a7fb5ec1fc2bc

**Comment by khronokernel** [comment]
Fixed here: https://github.com/dortania/dortania.ml/commit/146c99838843c001a78b4d3a5b6abf8cc46a99e4
